### ISSUE TITLE
Add quotes " to label values to make it easier to copy paste

### ISSUE THREAD

**Issue by lilic** [polarsignals/issues#1]
While clicking on the label is great way for me to narrow down the search, sometimes I want to copy the entire thing, label and value, to create my own custom query. But now I have to add an `"<my-fancy-label-value>"` to the label value to be able to query it. Is there any reason you dropped the` ""` from the label values?

tl;dr: Surrond label values with quotes "" :
<img width="385" alt="Screenshot 2021-03-11 at 14 53 13" src="https://user-images.githubusercontent.com/6232346/110797644-93f6a280-8279-11eb-9170-6292a2cfb682.png">

**Comment by brancz** [comment]
Whops, this was an oversight. We'll get this fixed.

**Comment by brancz** [comment]
We have fixed this in various places as part of the newly introduced [Cumulative Metrics feature](https://www.polarsignals.com/blog/posts/2021/03/23/continuous-profiler-cumulative-metrics/).
