### ISSUE TITLE
Undo comparison

### ISSUE THREAD

**Issue by yeya24** [polarsignals/issues#11]
I am not sure if it is already possible. If I miss anything, please let me know and I will close the pr.

With the current PolarSignals UI, if I click comparison, I cannot undo the comparison and go back to the first profile I selected.

What I want:
I can have a way to undo the comparison and go back to the first profile. Please let me know if this makes sense

Reproduce:
1. I query some profiles and chose one profile for more investigation
2. I clicked the `compare` button, maybe by accident
![image](https://user-images.githubusercontent.com/25150124/120386550-c3580100-c2f6-11eb-871b-968dd2d5880a.png)

3. I want to undo the comparison and go back to the original profile I selected (step 2). There is no `undo` button but I thought if I clicked the left profile, I can go back.
![image](https://user-images.githubusercontent.com/25150124/120386734-03b77f00-c2f7-11eb-914d-90e2af95a074.png)

4. I clicked it but it navigates me to the query page.

**Comment by brancz** [comment]
I think what you're suggesting makes a lot of sense, @metalmatze is working to improve the compare flow in general, maybe we can include this as part of that?

**Comment by metalmatze** [comment]
Yep. That should be possible to implement. 

It probably doesn't relate to the UI itself but rather how we generate the UI based on the router state.

**Comment by brancz** [comment]
We implemented this a while ago. It's possible to just X out the comparison and return to the previous exploration style querying.
