### ISSUE TITLE
Don't auto-create orgs and projects

### ISSUE THREAD

**Issue by brancz** [polarsignals/issues#14]
We initially thought that in order to optimize the first-time experience we automatically create organizations and projects for a user, but it turns out this is more confusing than helpful because in most cases there is a team that sets up Polar Signals for their organization and then invites users. In that model, every new user is confused about why they have 2 organizations: the one their colleague set up, and the one that was auto-created.

**Comment by brancz** [comment]
@manojVivek @monicawoj @yomete I think this feedback from a beta user makes sense. I think we should change the flow of how a user starts their journey through Polar Signals.

**Comment by monicawoj** [comment]
@brancz with that use case (being invited by someone else) in mind, I completely agree!

**Comment by yomete** [comment]
do we need to do anything on the frontend for this or it's on the backend side?

**Comment by brancz** [comment]
It's a bit of a combination, I think first, the backend should not create the organization and project automatically. I would suggest @manojVivek can take care of that part when he's back from PTO. On the frontend though, I think we should have a guided experience that guides the user through creating their first organization and project should they not have any (we could already trigger that by having one of us leave all organizations they're in).

**Comment by yomete** [comment]
That sounds good. I've gone ahead to create issues for both work streams - 
[#1078](https://github.com/polarsignals/polarsignals/issues/1078)
[#1077](https://github.com/polarsignals/polarsignals/issues/1077)

**Comment by manojVivek** [comment]
Sounds good, will look into it. 👍🏼

**Comment by brancz** [comment]
Resolved
