### ISSUE TITLE
Icicle bar shown too wide

### ISSUE THREAD

**Issue by bboreham** [polarsignals/issues#15]
Example: https://pprof.me/3ab37e9/
![image](https://user-images.githubusercontent.com/8125524/182575419-58f229f5-faaa-47b8-90e1-c7f02969faab.png)

That left-hand bar is 0.02% but shown about a third of the width.

**Comment by brancz** [comment]
Sorry that it’s taking so long, but @manojVivek is now working on reusing the parca components in sharing, so this should be fixed soon!

**Comment by manojVivek** [comment]
It's addressed in the new release.

<img width="1693" alt="Screenshot 2022-10-13 at 3 36 57 PM" src="https://user-images.githubusercontent.com/1283424/195568583-93b8e96f-6ad3-4773-89a4-efb0cbcdbb39.png">
