### ISSUE TITLE
pprof.me: chrome hard exits when clicking upload profile

### ISSUE THREAD

**Issue by asubiotto** [polarsignals/issues#18]
From a user:

Whenever I (on latest Chrome) click the "upload profile" button on [pprof.me](http://pprof.me/) my Chrome hard-exits.
https://www.loom.com/share/118102447c6c4405864384a863daad4d

I can reproduce this on my own laptop/chrome. Has anything changed recently?

**Comment by tbg** [comment]
This doesn't happen any more btw. Instead, it doesn't work in another way. When I want to upload a (heap) profile, I get

<img width="352" alt="image" src="https://github.com/polarsignals/issues/assets/5076964/d9ca048b-f8d7-40a7-b9fa-a2c68a252e3a">

**Comment by brancz** [comment]
@tbg could you share one of those profiles so we can try to reproduce this?

**Comment by tbg** [comment]
[delme.pb.gz](https://github.com/polarsignals/issues/files/12093663/delme.pb.gz)

**Comment by brancz** [comment]
Thank you! Investigating.

**Comment by brancz** [comment]
Could it be that it was just that one request that failed for some reason? I tried uploading that and it worked.

**Comment by tbg** [comment]
It's 100% for me. Maybe something is messed up with my Chrome. I will investigate and report back.

**Comment by tbg** [comment]
It is totally my Chrome work profile. It works fine in my private profile. There must be something messed up on my end. Sorry about the noise! At least we get to close this issue as a result (I am "the user" mentioned above and the hard exit has been fixed).

**Comment by brancz** [comment]
Sounds good! Always feel free to create a new issue and do please also comment if you figure out what is going on.
