### ISSUE TITLE
pprof.me: Filtered profile errors with `Showing NaN values.` 

### ISSUE THREAD

**Issue by javierhonduco** [polarsignals/issues#19]
I don't know if filtering caused the issue. This was a [profile from Demo](https://demo.parca.dev/?expression_a=parca_agent_cpu%3Asamples%3Acount%3Acpu%3Ananoseconds%3Adelta%7Bcomm%3D%22parca-agent%22%7D&from_a=1679908510929&to_a=1679909410929&time_selection_a=relative:minute|15&dashboard_items=icicle&merge_from_a=1679908510929&merge_to_a=1679909410929).

https://pprof.me/2289e8d/

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/959128/227901921-4ca25abd-2752-462b-89d4-efea0d8c3a6b.png">

**Comment by metalmatze** [comment]
pprof.me works again. This issue has been resolved.
