### ISSUE TITLE
Feature Request: Add last 3 days option to timepicker

### ISSUE THREAD

**Issue by lilic** [polarsignals/issues#2]
1 day tends to not be enough and 7 days too long. So 3 days for me tends to be the sweet spot when comparing/merging or searching. Not sure if that's just me. I understand there is the timepicker, but I tend to have to use it too frequently just to get 3 days. :D

**Comment by brancz** [comment]
I agree, the two are a bit extreme right now. This should be an easy addition.

**Comment by brancz** [comment]
Added this together with our cumulative metrics feature! :)
