### ISSUE TITLE
pprof.me: Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by bwplotka** [polarsignals/issues#21]
CPU profile causes "Application error: a client-side exception has occurred (see the browser console for more information)."

![image](https://github.com/polarsignals/issues/assets/6950331/21df459e-a2fe-48a4-89e9-cdcc5834cc42)

Console:

```
Error: <svg> attribute width: Expected length, "auto".
3instrument.js:108 TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at m (index.js:51:27)
    at cell (index.js:66:31)
    at Eo (react-dom.production.min.js:167:137)
    at xi (react-dom.production.min.js:290:337)
    at bs (react-dom.production.min.js:280:389)
    at gs (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at as (react-dom.production.min.js:271:88)
    at is (react-dom.production.min.js:273:300)
    at jl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonymous) @ instrument.js:108
instrument.js:108 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
(anonymous) @ instrument.js:108
react-dom.production.min.js:24 Error: <svg> attribute width: Expected length, "auto".
b @ react-dom.production.min.js:24
```

E.g. see https://pprof.me/cbe7f5d/?dashboard_items=table

Source file of the pprof profile taken from: https://github.com/prometheus/prometheus/discussions/12518#discussioncomment-6365981

[NP-CHI4-shard0-after-profile001.pb.gz](https://github.com/prometheus/prometheus/files/11960683/NP-CHI4-shard0-after-profile001.pb.gz)
[NP-CHI4-shard0-before-profile001.pb.gz](https://github.com/prometheus/prometheus/files/11960684/NP-CHI4-shard0-before-profile001.pb.gz)

**Comment by brancz** [comment]
Thanks for reporting! We’ll have to have a look at this!

**Comment by brancz** [comment]
@bwplotka this has been fixed, thank you for reporting. I did also have a look at this link and the data looks pretty odd, and then I checked and the raw data and it appears to be the raw data that's looking so odd. I think we can close this here since the raw data seems off, but how did these profiles get created?

**Comment by bwplotka** [comment]
Thanks, good question to https://github.com/prometheus/prometheus/discussions/12518#discussioncomment-6365981 

As long as there is clear error that profile data is odd - all good.

**Comment by brancz** [comment]
Here's a text form of the underlying protobuf for `NP-CHI4-shard0-after-profile001.pb.gz`: https://gist.github.com/brancz/0443f995b773c7c46903c4299cab4f95

As you can see, each `sample` only has a single location. That's also why the iciclegraph looks so flat.
