### ISSUE TITLE
Failure to symbolise some Mir frames

### ISSUE THREAD

**Issue by RAOF** [polarsignals/issues#24]
When profiling my miriway-shell session, I see a mix of resolved and unresolved symbols.
Profile is [https://pprof.me/840b1c207a8e01b05fc9edd97934e8fc](here).

An example stacktrace with symbols missing from `libmirplatform.so.27` is under `mir::compositor::DroppingSchedule::schedule()`.
[DSO with symbols that fail to resolve](https://github.com/polarsignals/issues/files/15334910/libmirplatform.so.27.gz)

**Comment by brancz** [comment]
Looks like we're getting there, I can no longer see missing symbols for `libmirplatform.so.27`, as far as I can see, we now only have a few symbols left that are not symbolized from:

* `libwayland-server.so.0.22.0`
* `libmirserver.so.59`
* `libstdc++.so.6.0.33`

We'll keep you up to date as we find out why and once we have it fixed.

**Comment by brancz** [comment]
Actually, after double-checking all of these, it seems we have fixed all of these cases. The unsymbolized frames in the shared profile continue to stay unsymbolized because it was a snapshot of the query at the time.

Thank you very much for reporting! 🥳
