### ISSUE TITLE
Add type of profile to labels

### ISSUE THREAD

**Issue by lilic** [polarsignals/issues#3]
While running a query I noticed the same container 5 times in the search results, at first I thought it might be a deduplication issue but it was just I did not select which type of profile to search for, so I had all profile types returned. It might help avoid confusion in the future by adding a profile type label to the labels.

These all look the same, unless you hover over them to see the type:

<img width="1183" alt="Screenshot 2021-03-11 at 15 07 28" src="https://user-images.githubusercontent.com/6232346/110799532-8b9f6700-827b-11eb-8d6c-1a35a83d5ebe.png">

**Comment by brancz** [comment]
Whops, yeah we actually used to have this, but it seems in some iteration it slipped away. We're currently re-working the query result display anyways, so hopefully this will be resolved with that as well.

**Comment by brancz** [comment]
We slightly changed the layout of everything and don't show labels like this anymore with our latest [Cumulative Metrics feature](https://www.polarsignals.com/blog/posts/2021/03/23/continuous-profiler-cumulative-metrics/), but we show the type of profile in the tooltip when hovering over samples.

Closing. And thank you so much for the feedback!
