### ISSUE TITLE
Use full width for displaying profiles on share.polarsignals.com

### ISSUE THREAD

**Issue by metalmatze** [polarsignals/issues#4]
It'd be great to simply use the full width. I can see a `col-8 col-offset-2`, but this becomes quite a drastic margin with a super wide screen monitor. I'd rather spend the space looking at profiles :upside_down_face: 
![share polarsignals com_d05ce26_](https://user-images.githubusercontent.com/872251/110924632-9234e980-8322-11eb-8f8d-fe73db2c1d25.png)

Basically asking: Is it possible to simply use `col-12`? :)

**Comment by brancz** [comment]
Definitely! We should do this!

**Comment by brancz** [comment]
Rolled out the change yesterday. Enjoy!
