### ISSUE TITLE
Same series shortcut when selecting profiles to compare

### ISSUE THREAD

**Issue by yeya24** [polarsignals/issues#6]
When I select one profile and I want to compare it with another profile from the same series, I have to enter the series matchers again manually.

It would be good to have a button with text like `compare with the same series` so that the input can be filled with the same matchers by clicking it.

![Screenshot from 2021-03-30 13-56-25](https://user-images.githubusercontent.com/25150124/113034128-c0f2f280-915f-11eb-9d99-d5601320866a.png)

**Comment by brancz** [comment]
Yeah, I 100% agree. I have even thought of just defaulting directly to the same label set as the first selection, or the same query as what was used for the first selection. Would you have a preference?

**Comment by yeya24** [comment]
I prefer the latter. But either way is good to me!

**Comment by brancz** [comment]
Ok awesome! I hope to find some time in the next weeks to do this. Thank you for your feedback!

**Comment by yeya24** [comment]
I think this is done. Thanks @metalmatze
