### ISSUE TITLE
Selecting larger timeframe then available data stretches graph

### ISSUE THREAD

**Issue by lilic** [polarsignals/issues#7]
When I only sent one hour worth of data, but search for one day it seems to stretch the graph to full window which skews the data points.

One day selected:
![Screenshot 2021-04-07 at 11 28 08](https://user-images.githubusercontent.com/6232346/113844082-69263e00-9794-11eb-9d7f-8460b512d63f.png)

Selected all available in that graph via drag-select:
![Screenshot 2021-04-07 at 11 28 24](https://user-images.githubusercontent.com/6232346/113844117-74796980-9794-11eb-9f98-da7ffe8a0361.png)

This shows correct results.

**Comment by brancz** [comment]
This is fixed.
